import { LanguageType } from "../types/languageTypes";

export const languageEnum: Record<LanguageType, LanguageType> = {
  en: "en",
  de: "de",
};

export const translations: Record<LanguageType, Record<string, string>> = {
  en: {
    title1:
      "Computer Science Expert Subject Area: Software Development in training",
    company1: "Energieversum GmbH & Co KG",
    date1: "2024-2026",
    bullets1:
      "Implementing applications in Microsoft Dynamics, using React, TypeScript, JavaScript, C#, and Fluent UI.\nImplemented industry standards and help improve work structure.\nWorkshops for Power Apps Component Frameworks.",
    title2: "Working studen Software Engineering",
    company2: "Valuedesk GmbH",
    date2: "2019-2024",
    bullets2:
      "Extending existing software solutions, using React, TypeScript and Material UI\nImplementation of small solutions.\nTesting and bug fixes.",
    home: "Home",
    name: "Name",
    portfolio: "My Portfolio",
    email: "Email",
    message: "Message",
    experiences: "Experiences",
    experiencesPage: "Experiences in Software Development",
    contact: "Contact",
    sendingMessage: "Sending message ...",
    messageSend: "Send Message",
    welcome: "Hello, I'm Dennis Butenko",
    projects: "Projects",
    summary:
      "As a software developer, I combine clean, scalable code with a clear focus on user-friendliness – for applications that not only work but also inspire.",
    theme: "Theme",
    language: "Language",
    sendFailed: "Failed to send message",
    messageSent: "Message sent — thank you!",
    somethingWentWrong: "Something went wrong",
    "Bingo Projekt": "Bingo Project",
    Digiform: "Digiform",
    Vertriebscheckliste: "Sales Checklist",
    "Digiform Berufskolleg": "Digiform Vocational College",
    "Portfolio Webseite": "Portfolio Website",
    "IT Bedrohung": "IT Threat",
    "Abschlussprojekt Ausbildung": "Final Project Traning",
  },
  de: {
    title1: "Fachinformatiker Anwendungsentwicklung in Ausbildung",
    company1: "Energieversum GmbH & Co KG",
    date1: "2024-2026",
    bullets1:
      "Implementation von Anwendungen in Microsoft Dynamics, mithilfe von React, TypeScript, JavaScript, C# und Fluent UI.\nImplementation von Branchen Standards und Beihilfe zur verbesserten Arbeitsstrucktur.\nWorkshops für Power Apps Component Frameworks.",
    title2: "Werkstudent Softwareentwicklung",
    company2: "Valuedesk GmbH",
    date2: "2021-2024",
    bullets2:
      "Erweiterung bestehender Softwarelösungen, mithilfe von React, TypeScript und Material UI\nImplementation von kleinen Lösungen.\nTesting und Bug Behebungen.",
    home: "Start",
    name: "Name",
    email: "E-Mail",
    message: "Nachricht",
    sendingMessage: "Nachricht wird verschickt ...",
    messageSend: "Abschicken",
    portfolio: "Mein Portfolio",
    experiences: "Erfahrungen",
    experiencesPage: "Erfahrungen in der Softwareentwicklung",
    contact: "Kontakt",
    welcome: "Hallo, ich bin Dennis Butenko",
    projects: "Projekte",
    summary:
      "Als Softwareentwickler verbinde ich sauberen, skalierbaren Code mit einem klaren Fokus auf Nutzerfreundlichkeit – für Anwendungen, die nicht nur funktionieren, sondern begeistern.",
    theme: "Thema",
    language: "Sprache",
    sendFailed: "Nachricht konnte nicht verschickt werden",
    messageSent: "Nachricht verschickt — vielen Dank!",
    somethingWentWrong: "Etwas ist schief gelaufen",
    "Bingo Projekt": "Bingo Projekt",
    Digiform: "Digiform",
    Vertriebscheckliste: "Vertriebscheckliste",
    "Digiform Berufskolleg": "Digiform Berufskolleg",
    "Portfolio Webseite": "Portfolio Webseite",
    "IT Bedrohung": "IT Bedrohung",
    "Abschlussprojekt Ausbildung": "Abschlussprojekt Ausbildung",
  },
};
